---
functional:
  - Пользователь должен иметь вомзожность зарегистрироваться с помощью GitHub/ Discord
  - Пользователь должен иметь возможность создавать игры
  - Пользователь должен иметь вомзожность общаться в чате с другими игроками 
  - Пользователь должен иметь возможность просматривать другие турниры
  - Пользователь должен иметь возможность создавать задачи, просматривать задачи и пакеты задач
  - Пользователь должен иметь возможность просматривать рейтинг пользователей по страницам
  - Пользователь должен иметь возможность сортировать рейтинг пользователей 
  - Пользователь должен иметь возможность выполнять поиск пользователей в рейтинге по имени
  - Пользователь может просматривать данные своего профиля (статистику и завершенные игры)
  - Пользователь может отправить сообщение любому игорку 
  - Пользователь может бросить вызов любому игорку 
  - Пользователь должен иметь вомзожность просматривать уведомления и общие оповещения
  - Пользователь должен иметь вомзожность просматривать идущие и завершенные туррины и информацию о них
  - Пользователь может просматривать историю сражений
  - Пользователь может просматривать таблицу лидеров по периодам  (ежемесячно, еженедельно, в общем)
  - Пользователь может попробовать игру без регистрации
non-functional:
  - Сайт с игрой должен быть безопасным и защищать данные пользователя
  - Сайт с игрой должен быть адаптирован для мобильных устройств 
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров (Google Chrome, Yandex) 
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
implicit:
  - Должна быть возможность переключения между языками (русский, английский)
  - Пользователь может просматривать профиль другого игрока (статистика, достижения и завершенные игры)
  - Пользователь может отслеживать появление выбранного игрока
  - Пользователь может удалить свой профиль
  - Все элементы игры должны быть понятны. При наведении на инфографику стрелкой мыши должна высвечиваться подпись с информацией об элементе
  - В одной игре могут состязаться только 2 игрока 
  - Пользователь может восстановить пароль
  - Для вновь зарегистрированных пользователей 
