functional:
  - Пользователь должен иметь вомзожность зарегистрироваться с помощью GitHub/ Discord
  - Пользователь должен иметь возможность создавать игры
  - 
non-functional:
  - Сайт с игрой должен быть безопасным и защищать данные пользователя
  - Сайт с игрой должен быть адаптирован для мобильных устройств 
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
implicit:
  - требование 5
  - требование 6
