---
functional:
  - Пользователь должен иметь вомзожность зарегистрироваться с помощью GitHub/ Discord
  - Пользователь должен иметь возможность создавать игры
  - Пользователь должен иметь вомзожность общаться в чате с другими игроками 
  - Пользователь должен иметь возможность просматривать другие турниры
  - Пользователь должен иметь возможность создавать задачи, просматривать задачи и пакеты задач
  - Пользователь должен иметь возможность просматривать рейтинг пользователей по страницам
  - Пользователь должен иметь возможность сортировать рейтинг пользователей 
  - Пользователь должен иметь возможность выполнять поиск пользователей в рейтинге по имени
  - Пользователь может просматривать данные своего профиля (статистику и завершенные игры)
  - Пользователь может отправить сообщение любому игорку или бросить вызов
  - Пользователь должен иметь вомзожность просматривать уведомления и общие оповещения
  - Пользователь должен иметь вомзожность просматривать идущие и завершенные туррины и информацию о них
  - Пользователь может просматривать историю сражений
  - Пользователь может просматривать таблицу лидеров по периодам  (ежемесячно, еженедльно, в общем)
  - Пользователь может попробовать игру без регистрации
non-functional:
  - Сайт с игрой должен быть безопасным и защищать данные пользователя
  - Сайт с игрой должен быть адаптирован для мобильных устройств 
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
implicit:
  -Пользователь имеет возможность посмотреть какие пользователи сейчас онлайн
  - Пользователь может просматривать профиль другого игрока (статистика, достижения и завершенные игры)
  - Пользователь может посомтреть исходный код проекта
  - Пользователь может перейти на сайт Хекслет, присоединиться в Дискорд и (или) к ТГ каналу Codebattle
  - Пользователь может отслеживать появление выбранного игрока
  - За открытой игрой может наблюдать пользователь без посещения сайта
  - Пользователь может удалить свой профиль (логин)
  - При наведении на инфографику стрелкой мыши должна высвечиваться подпись с информацией об элементе
  - В одной игре могут состязаться только 2 игрока 
  - Пользователь может восстановить пароль 
